### ISSUE TITLE
Empty key's are valid JSON but fails to parse 

### ISSUE THREAD

**Issue by jakelandis** [logstash-plugins/logstash-codec-json#35] opened 2017-12-11 19:10 UTC
```
bin/logstash -e 'input { stdin { codec => json_lines } } output { stdout { codec => rubydebug } }'
```
With this input:
```
{"Production number":"12345678","":""}
```
Results in 
```
[2017-12-11T11:53:49,376][WARN ][logstash.codecs.jsonlines] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: -1>, :data=>"{\"Production number\":\"12345678\",\"\":\"\"}"}
{
       "message" => "{\"Production number\":\"12345678\",\"\":\"\"}",
      "@version" => "1",
          "host" => "mbp15r",
          "tags" => [
        [0] "_jsonparsefailure"
    ],
    "@timestamp" => 2017-12-11T16:53:49.378Z
}
```

**Comment by jakelandis** [comment] 2017-12-18 15:50
I _think_ this may have been fixed by https://github.com/elastic/logstash/issues/8823.  I can not reproduce now with that fix.

**Comment by jsvd** [comment] 2017-12-18 16:12
@jakelandis I also can't reproduce that issue anymore with the patch to 6.1, I think we can close this.

**Closed as completed** 2017-12-18 16:15 UTC
