### ISSUE TITLE
"Incompatible encoding" when using Logstash to ship JSON files to Elasticsearch

### ISSUE THREAD

**Issue by object** [logstash-plugins/logstash-codec-json#1] opened 2014-12-10 20:51 UTC
We have been successfully using Logstash to parse our JSON logs data and import them to Elasticsearch database, but recently had failures on some machines. Here's the error Logstash displays:

←[32mRegistering file input {:path=>["D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/BridgeSoap._.txt"], :level=>:info}←[0m
←[32mPipeline started {:level=>:info}←[0m
←[31mA plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::File add_field=>{"_environment"=>"prod-ndoa", "_application"=>"bridge_rest"}, path=>["D:/Octopus/Applications/prod-ndoa/Bridge.Rest.Host/logs/BridgeRest._.txt"], sincedb_path=>"D:/Octopus/Applications/prod-ndoa/Bridge.Rest.Host/logs/sincedb",tags=>["bridge_rest"], start_position=>"end">
  Error: incompatible encodings: Windows-1252 and UTF-8 {:level=>:error}←[0m

The input file is a set of JSON documents in UTF-8 encoding (with BOM). If edit the file and remove BOM symbols, the import goes fine.

And here's the input file configuration:

input {
  file {
    path => "D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/BridgeSoap.*.txt"
    sincedb_path => "D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/sincedb"
    codec => json
    start_position => "end"
   }
}

If I remove codec "json", it doesn't fail but the output of course is wrong because it treats JSON documents as plain text.

The strangest things is that on other machines it works properly (same 1.4.2 version of Logstash).

**Comment by jordansissel** [comment] 2014-12-10 22:00
I was digging into BOM, Ruby, standards, etc - and what a fun time. Check this out, from wikipedia on By order mark -

> The Unicode Standard permits the BOM in UTF-8,[2] but does not require or recommend its use.[3] Byte order has no meaning in UTF-8,[4] so its only use in UTF-8 is to signal at the start that the text stream is encoded in UTF-8.

So it's called "byte order mark" but it's meaningless because UTF-8 has no byte ordering so it's useless. What is this madness?

---

**Comment by jordansissel** [comment] 2014-12-10 22:03
Well, this is easy to reproduce -

```
>> puts [0xEF,0xBB,0xBF, {"Hello" => "World"}.to_json].pack("C3A*").force_encoding("UTF-8")
{"Hello":"World"}
=> nil
>> JSON.parse([0xEF,0xBB,0xBF, {"Hello" => "World"}.to_json].pack("C3A*").force_encoding("UTF-8"))
JSON::ParserError: 757: unexpected token at '{"Hello":"World"}'
        from /Users/jls/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/json/common.rb:155:in `parse'
        from /Users/jls/.rvm/rubies/ruby-2.1.4/lib/ruby/2.1.0/json/common.rb:155:in `parse'
        from (irb):19
        from /Users/jls/.rvm/rubies/ruby-2.1.4/bin/irb:11:in `<main>'
```

Using a Unicode BOM causes Ruby's JSON parser to fail.

**Comment by jordansissel** [comment] 2014-12-10 22:13
Ruby's json parser also seems to reject much of what Unicode whitespace glyphs are available:

```
whitespace = [ 0x9, 0xA, 0xB, 0xC, 0xD, 0x20, 0x85, 0xA0, 0x1680, *(0x2000..0x200A), 0x2028, 0x2029, 0x202f, 0x205f, 0x3000 ].collect { |v| eval(sprintf("\"\\u%04x\"", v)) }
JSON.parse(whitespace.shuffle[0..rand(whitespace.count)].join("") + "{}")
```

Most of the attempts to parse the whitespace-prefixed json fails in Ruby with most whitespace characters.

**Comment by jordansissel** [comment] 2014-12-10 22:16
Python's json parser also fails if BOM is present.

**Comment by object** [comment] 2014-12-11 00:27
Interesting! I will inspect our code to find out what makes it insert BOMs into UTF-8 files. Thank you for a quick response.

**Comment by jordansissel** [comment] 2014-12-11 00:31
@object cool :)

Ultimately, logstash could provide a way to handle this kind of thing, but if you can improve the data before input, that also works :)

**Comment by object** [comment] 2014-12-11 06:45
I haven't investigated it yet but apparently this is caused by one of the logging library we're using so if we don't manage to tweak its output, I'd be very interested to find how Logstash can handle it. Can you give me some hint for how we should configure Logstash so it will accept an UTF-8 file with BOM?

**Comment by object** [comment] 2014-12-11 06:49
And BTW, I am now puzzled to understand how this could possible work on other machines. We have several nodes using (or at least supposed to be using) the same versions of our and logstash software. And we had no problems with other nodes, it's just when I configured a new node this started happening.

**Comment by object** [comment] 2014-12-11 09:01
I have inspected log files on other machines, and yes, it _mostly_ works with BOM. Now I am really confused what's so special with some machines. You're saying "Most of the attempts to parse the whitespace-prefixed json fails in Ruby". Shouldn't it be predictable, i.e. either fail or not?

**Comment by colinsurprenant** [comment] 2014-12-12 00:35
@object What Logstash version are you using? I do not see where this `Error: incompatible encodings: Windows-1252 and UTF-8` comes from... what @jordansissel showed is that a JSON document will not parse if it starts with a BOM and fails with the `unexpected token` exception. I think these are 2 different issues IMO. 

@object Could you provide a sample log which contains a BOM and produces your exception?

One thing we know is that a json document with a leading BOM will go through our charset validation:

``` sh
>> bom = "\xEF\xBB\xBF{\"hello\":\"world\"}"
=> "{\"hello\":\"world\"}"
>> bom.encoding
=> #<Encoding:UTF-8>
>> bom.valid_encoding?
=> true
>> JSON.parse(bom)
JSON::ParserError: unexpected token at '{"hello":"world"}'

```

We could add an option at the codec to force-cleanse the input? something like:

``` sh
>> bom.force_encoding("ASCII-8BIT")
=> "\xEF\xBB\xBF{\"hello\":\"world\"}"
>> clean = bom.encode(Encoding::UTF_8, :invalid => :replace, :undef => :replace, :replace => "")
=> "{\"hello\":\"world\"}"
>> JSON.parse(clean)
=> {"hello"=>"world"}
```

**Comment by object** [comment] 2014-12-12 06:30
@colinsurprenant I am using logstash 1.4.2. I will reproduce the issue and paste the content of the error output.

**Comment by object** [comment] 2014-12-12 12:43
@colinsurprenant, @jordansissel, here are more details:
1. Logstash version is 1.4.2 (the latest one).
2. System: Windows Server 2008
3. Logstash command line: logstash agent -f config/bridge.conf --verbose
4. The content of bridge.conf:

```
input {
  file {
    add_field => { "_environment" => "prod-ndoa" }
    add_field => { "_application" => "bridge_soap" }
    path => "D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/test/BridgeSoap.*.txt"
    sincedb_path => "D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/sincedb"
    codec => json
    tags => [bridge_soap]
    start_position => "beginning"
   }
}
output {
  elasticsearch_http {
    host => "maindeks01"
    port => 9200
    index => "logstash-prod-ndoa-bridge_soap-%{+YYYY.MM}"
    flush_size => 10
    template => "config/bridge.template.json"
    manage_template => true
  }
}
```
1. The error message:

```
C:\Program Files (x86)\Logstash\logstash-1.4.2>bin\logstash agent -f config/bridge.conf --verbose

←[33mUsing milestone 2 input plugin 'file'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, seehttp://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}←[0m

←[33mUsing milestone 2 output plugin 'elasticsearch_http'. This plugin should be stable, but if you see strange behavior, please let us know! For more information on plugin milestones, see http://logstash.net/docs/1.4.2/plugin-milestones {:level=>:warn}←[0m

←[32mRegistering file input {:path=>["D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/test/BridgeSoap.*.txt"], :level=>:info}←[0m

←[32mPipeline started {:level=>:info}←[0m

←[31mA plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::File add_field=>{"_environment"=>"prod-ndoa", "_application"=>"bridge_soap"}, path=>["D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/test/BridgeSoap.*.txt"],sincedb_path=>"D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/sincedb", tags=>["bridge_soap"], start_position=>"beginning">
  Error: incompatible encodings: Windows-1252 and UTF-8 {:level=>:error}←[0m

←[33mInterrupt received. Shutting down the pipeline. {:level=>:warn}←[0m
```
1. Finally, the content of the log file (NB! to make logstash fail you should save it with UTF-8 BOM):

```
{"Timestamp":"2014-12-01T00:00:13.2834210+01:00","Level":"Debug","MessageTemplate":"Fetching all changes from domain {Domain} since {SinceTime} (UTC: {SinceUTC})","RenderedMessage":"Fetching all changes from domain \"ndoa\" since 11/30/2014 13:42:14 (UTC: 11/30/2014 12:42:14)","Properties":{"Domain":"ndoa","SinceTime":"2014-11-30T13:42:14.0000000+01:00","SinceUTC":"2014-11-30T12:42:14.0000000Z"}}
{"Timestamp":"2014-12-01T00:00:13.2990212+01:00","Level":"Debug","MessageTemplate":"Search called for provider {ProviderName} with query={Query}","RenderedMessage":"Search called for provider \"g3db\" with query=\"Bridge.AssetService.G3.Queries.G3DbNotificationsByDateTimeQuery\"","Properties":{"ProviderName":"g3db","Query":"Bridge.AssetService.G3.Queries.G3DbNotificationsByDateTimeQuery","clientIp":"2002:a044:1512::a044:1512","sessionId":null}}
{"Timestamp":"2014-12-01T00:00:13.2990212+01:00","Level":"Debug","MessageTemplate":"Querying database for modified clips (including metadata-changed) newer than {ModifiedDate}","RenderedMessage":"Querying database for modified clips (including metadata-changed) newer than 11/30/2014 13:42:14","Properties":{"ModifiedDate":"2014-11-30T13:42:14.0000000+01:00","clientIp":"2002:a044:1512::a044:1512","sessionId":null}}
{"Timestamp":"2014-12-01T00:00:13.3146214+01:00","Level":"Debug","MessageTemplate":"Getting modified clips from G3 SQL: {ModifiedClips}","RenderedMessage":"Getting modified clips from G3 SQL: \"SELECT \r\n[Project2].[FLE_ID] AS [FLE_ID], \r\ncast(0 as bit) AS [C1], \r\n[Project2].[C2] AS [C2], \r\n[Extent3].[FLE_sharer_path] AS [FLE_sharer_path], \r\n[Extent4].[CLP_clip_title] AS [CLP_clip_title], \r\n[Project2].[C1] AS [C3]\r\nFROM    (SELECT \r\n\t[Project1].[C1] AS [C1], \r\n\t[Project1].[FLE_ID] AS [FLE_ID], \r\n\t(SELECT \r\n\t\tCOUNT(1) AS [A1]\r\n\t\tFROM [dbo].[g3Media_FCH_FileChanges] AS [Extent2]\r\n\t\tWHERE ([Extent2].[FCH_Date_Written] > @p__linq__0) AND ([Project1].[FLE_ID] = [Extent2].[FLE_ID]) AND (1 <> [Extent2].[FCT_ID])) AS [C2]\r\n\tFROM ( SELECT \r\n\t\t[GroupBy1].[A1] AS [C1], \r\n\t\t[GroupBy1].[K1] AS [FLE_ID]\r\n\t\tFROM ( SELECT \r\n\t\t\t[Extent1].[FLE_ID] AS [K1], \r\n\t\t\tMAX([Extent1].[FCH_Date_Written]) AS [A1]\r\n\t\t\tFROM [dbo].[g3Media_FCH_FileChanges] AS [Extent1]\r\n\t\t\tWHERE [Extent1].[FCH_Date_Written] > @p__linq__0\r\n\t\t\tGROUP BY [Extent1].[FLE_ID]\r\n\t\t)  AS [GroupBy1]\r\n\t)  AS [Project1] ) AS [Project2]\r\nINNER JOIN [dbo].[OmniBus_FLE_Files] AS [Extent3] ON [Project2].[FLE_ID] = [Extent3].[FLE_ID]\r\nINNER JOIN [dbo].[OmniBus_CLP_Clips] AS [Extent4] ON [Project2].[FLE_ID] = [Extent4].[FLE_ID]\r\nWHERE (0 = [Extent3].[FLE_file_deleted]) AND (0 = [Extent3].[FLE_file_dustbinned])\"","Properties":{"ModifiedClips":"SELECT \r\n[Project2].[FLE_ID] AS [FLE_ID], \r\ncast(0 as bit) AS [C1], \r\n[Project2].[C2] AS [C2], \r\n[Extent3].[FLE_sharer_path] AS [FLE_sharer_path], \r\n[Extent4].[CLP_clip_title] AS [CLP_clip_title], \r\n[Project2].[C1] AS [C3]\r\nFROM    (SELECT \r\n\t[Project1].[C1] AS [C1], \r\n\t[Project1].[FLE_ID] AS [FLE_ID], \r\n\t(SELECT \r\n\t\tCOUNT(1) AS [A1]\r\n\t\tFROM [dbo].[g3Media_FCH_FileChanges] AS [Extent2]\r\n\t\tWHERE ([Extent2].[FCH_Date_Written] > @p__linq__0) AND ([Project1].[FLE_ID] = [Extent2].[FLE_ID]) AND (1 <> [Extent2].[FCT_ID])) AS [C2]\r\n\tFROM ( SELECT \r\n\t\t[GroupBy1].[A1] AS [C1], \r\n\t\t[GroupBy1].[K1] AS [FLE_ID]\r\n\t\tFROM ( SELECT \r\n\t\t\t[Extent1].[FLE_ID] AS [K1], \r\n\t\t\tMAX([Extent1].[FCH_Date_Written]) AS [A1]\r\n\t\t\tFROM [dbo].[g3Media_FCH_FileChanges] AS [Extent1]\r\n\t\t\tWHERE [Extent1].[FCH_Date_Written] > @p__linq__0\r\n\t\t\tGROUP BY [Extent1].[FLE_ID]\r\n\t\t)  AS [GroupBy1]\r\n\t)  AS [Project1] ) AS [Project2]\r\nINNER JOIN [dbo].[OmniBus_FLE_Files] AS [Extent3] ON [Project2].[FLE_ID] = [Extent3].[FLE_ID]\r\nINNER JOIN [dbo].[OmniBus_CLP_Clips] AS [Extent4] ON [Project2].[FLE_ID] = [Extent4].[FLE_ID]\r\nWHERE (0 = [Extent3].[FLE_file_deleted]) AND (0 = [Extent3].[FLE_file_dustbinned])","clientIp":"2002:a044:1512::a044:1512","sessionId":null}}
{"Timestamp":"2014-12-01T00:00:13.3146214+01:00","Level":"Debug","MessageTemplate":"Querying database for deleted clips newer than {ModifiedDate}","RenderedMessage":"Querying database for deleted clips newer than 11/30/2014 13:42:14","Properties":{"ModifiedDate":"2014-11-30T13:42:14.0000000+01:00","clientIp":"2002:a044:1512::a044:1512","sessionId":null}}
{"Timestamp":"2014-12-01T00:00:13.3146214+01:00","Level":"Debug","MessageTemplate":"Getting deleted clips from G3 SQL: {DeletedClips}","RenderedMessage":"Getting deleted clips from G3 SQL: \"SELECT \r\n[Project1].[C3] AS [C1], \r\n[Project1].[C2] AS [C2], \r\n[Project1].[FLE_sharer_path] AS [FLE_sharer_path], \r\n[Project1].[CLP_clip_title] AS [CLP_clip_title], \r\n[Project1].[C1] AS [C3]\r\nFROM ( SELECT \r\n\t[GroupBy1].[A1] AS [C1], \r\n\t[Extent2].[FLE_sharer_path] AS [FLE_sharer_path], \r\n\t[Extent2].[FLE_date_modified] AS [FLE_date_modified], \r\n\t[Extent3].[CLP_clip_title] AS [CLP_clip_title], \r\n\tcast(1 as bit) AS [C2], \r\n\t0 AS [C3]\r\n\tFROM    (SELECT \r\n\t\t[Extent1].[FLE_ID] AS [K1], \r\n\t\tMAX([Extent1].[FCH_Date_Written]) AS [A1]\r\n\t\tFROM [dbo].[g3Media_FCH_FileChanges] AS [Extent1]\r\n\t\tWHERE [Extent1].[FCH_Date_Written] > @p__linq__0\r\n\t\tGROUP BY [Extent1].[FLE_ID] ) AS [GroupBy1]\r\n\tINNER JOIN [dbo].[OmniBus_FLE_Files] AS [Extent2] ON [GroupBy1].[K1] = [Extent2].[FLE_ID]\r\n\tINNER JOIN [dbo].[OmniBus_CLP_Clips] AS [Extent3] ON [GroupBy1].[K1] = [Extent3].[FLE_ID]\r\n\tWHERE [Extent2].[FLE_file_deleted] = 1 OR [Extent2].[FLE_file_dustbinned] = 1\r\n)  AS [Project1]\r\nORDER BY [Project1].[FLE_date_modified] ASC\"","Properties":{"DeletedClips":"SELECT \r\n[Project1].[C3] AS [C1], \r\n[Project1].[C2] AS [C2], \r\n[Project1].[FLE_sharer_path] AS [FLE_sharer_path], \r\n[Project1].[CLP_clip_title] AS [CLP_clip_title], \r\n[Project1].[C1] AS [C3]\r\nFROM ( SELECT \r\n\t[GroupBy1].[A1] AS [C1], \r\n\t[Extent2].[FLE_sharer_path] AS [FLE_sharer_path], \r\n\t[Extent2].[FLE_date_modified] AS [FLE_date_modified], \r\n\t[Extent3].[CLP_clip_title] AS [CLP_clip_title], \r\n\tcast(1 as bit) AS [C2], \r\n\t0 AS [C3]\r\n\tFROM    (SELECT \r\n\t\t[Extent1].[FLE_ID] AS [K1], \r\n\t\tMAX([Extent1].[FCH_Date_Written]) AS [A1]\r\n\t\tFROM [dbo].[g3Media_FCH_FileChanges] AS [Extent1]\r\n\t\tWHERE [Extent1].[FCH_Date_Written] > @p__linq__0\r\n\t\tGROUP BY [Extent1].[FLE_ID] ) AS [GroupBy1]\r\n\tINNER JOIN [dbo].[OmniBus_FLE_Files] AS [Extent2] ON [GroupBy1].[K1] = [Extent2].[FLE_ID]\r\n\tINNER JOIN [dbo].[OmniBus_CLP_Clips] AS [Extent3] ON [GroupBy1].[K1] = [Extent3].[FLE_ID]\r\n\tWHERE [Extent2].[FLE_file_deleted] = 1 OR [Extent2].[FLE_file_dustbinned] = 1\r\n)  AS [Project1]\r\nORDER BY [Project1].[FLE_date_modified] ASC","clientIp":"2002:a044:1512::a044:1512","sessionId":null}}
{"Timestamp":"2014-12-01T00:00:13.3146214+01:00","Level":"Debug","MessageTemplate":"Search for query={Query} returned from provider {ProviderName} after {Elapsed} milliseconds","RenderedMessage":"Search for query=\"Bridge.AssetService.G3.Queries.G3DbNotificationsByDateTimeQuery\" returned from provider \"g3db\" after 15 milliseconds","Properties":{"Query":"Bridge.AssetService.G3.Queries.G3DbNotificationsByDateTimeQuery","ProviderName":"g3db","Elapsed":15,"clientIp":"2002:a044:1512::a044:1512","sessionId":null}}
{"Timestamp":"2014-12-01T00:00:13.3146214+01:00","Level":"Debug","MessageTemplate":"G3DbChangesProvider: Got {ChangeCount} changes from G3 Db for domain {Domain}","RenderedMessage":"G3DbChangesProvider: Got 1 changes from G3 Db for domain \"NDOA\"","Properties":{"ChangeCount":1,"Domain":"NDOA"}}
{"Timestamp":"2014-12-01T00:00:13.3146214+01:00","Level":"Debug","MessageTemplate":"Setting InitialRun = {InitialRun} for domain {Domain} - lastNotification.Value = {LastNotification}","RenderedMessage":"Setting InitialRun = False for domain \"NDOA\" - lastNotification.Value = \"30.11.2014 12:42:14\"","Properties":{"InitialRun":false,"Domain":"NDOA","LastNotification":"30.11.2014 12:42:14"}}
{"Timestamp":"2014-12-01T00:00:13.3146214+01:00","Level":"Debug","MessageTemplate":"Removed {RemovedClipCount} clips from change list as they have just been indexed. {CachedClipCount} clips left.","RenderedMessage":"Removed 1 clips from change list as they have just been indexed. 0 clips left.","Properties":{"RemovedClipCount":1,"CachedClipCount":0}}
```

**Comment by object** [comment] 2014-12-12 12:46
And to make it easier, I created a gist with the log file: https://gist.github.com/object/593c46ebd31b1bcd49c8#file-bridgesoap-20141201-txt

But I believe any file will do, as along as it is saved with the BOM.

**Comment by colinsurprenant** [comment] 2014-12-15 19:47
@object could you try this for me please, change you input config to set the codec charset to Windows-1252 and rerun your test.

``` ruby
input {
  file {
    add_field => { "_environment" => "prod-ndoa" }
    add_field => { "_application" => "bridge_soap" }
    path => "D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/test/BridgeSoap.*.txt"
    sincedb_path => "D:/Octopus/Applications/prod-ndoa/Bridge.Web/logs/sincedb"
    codec => json {
      charset => "Windows-1252"
    }
    tags => [bridge_soap]
    start_position => "beginning"
  }
}
```

**Comment by jordansissel** [comment] 2014-12-15 20:15
@object Can you clarify your situation? Are these files with BOM only created when you hand-edit a file (like with Notepad), or are they created by normal server software running on your machines?

**Comment by jordansissel** [comment] 2014-12-15 20:16
> Most of the attempts to parse the whitespace-prefixed json fails in Ruby

By "most" I mean of the 20-ish kinds of whitespace in the Unicode set, most kinds of whitespace characters re rejected consistently as invalid sequences by the standard Ruby json parser (Same for Python). This is despite the json.org suggesting that "whitespace" is ignorable, in practice this seems to clearly not indicate which kinds of whitespace are considered OK by JSON.

**Comment by object** [comment] 2014-12-15 21:43
@colinsurprenant I may not be able to try it before Wednesday, but as soon as I reach that machine, I will try and let you know.

**Comment by object** [comment] 2014-12-15 21:45
@jordansissel These files are created by normal server running on our machines, but I can reproduce the problem by manually editing the files and saving them with BOM header. As I wrote earlier, the strangest thing is that on certain machines it never failed, and I have no explanation for that.

**Comment by object** [comment] 2014-12-17 13:03
@colinsurprenant I tried to run Logstash with the modified configuration (Windows-1252) but it didn't help. Still incompatible encoding. And btw the byte sequence is EF, BB, BF.

**Comment by jsvd** [comment] 2015-09-04 09:22
@object is this still a problem for you?

**Comment by object** [comment] 2015-09-04 11:28
Unfortunately I am not on that project now, can't verify.

**Comment by untergeek** [comment] 2016-04-26 17:04
Closing due to lack of update.  Feel free to re-open, or open a new ticket if needed.

**Closed as completed by untergeek** 2016-04-26 17:04 UTC
Labels: bug, unconfirmed

**Comment by PhaedrusTheGreek** [comment] 2017-02-24 16:53
@jordansissel @untergeek @colinsurprenant I am hitting this issue.  Seems that when a file has BOM, the JSON parser goes crazy.     What is the status of this issue?  Would a reproduction be helpful?

**Comment by jordansissel** [comment] 2017-02-24 17:43
@PhaedrusTheGreek let's get a new ticket open for this.

**Comment by damisul** [comment] 2020-10-07 10:39
Now seeing this error
Logstash 6.8 on Ubuntu 20.04

If JSON file has BOM I got an error: 
[2020-10-07T06:31:31,010][ERROR][logstash.codecs.json     ] JSON parse error, original data now in message field {:error=>#<LogStash::Json::ParserError: Unexpected character ('ï»¿' (code 65279 / 0xfeff)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')

If I remove BOM from file it loads just fine.
